-- BRD questions
-- 1. Which hospitals have the highest patient and operational activity?
SELECT
    h.hospital_id,
    h.hospital_name,

    (SELECT COUNT(*)
     FROM Appointments a
     WHERE a.hospital_id = h.hospital_id) AS total_appointments,

    (SELECT COUNT(*)
     FROM Admissions ad
     WHERE ad.hospital_id = h.hospital_id) AS total_admissions,

    (SELECT COUNT(*)
     FROM Laboratory l
     WHERE l.hospital_id = h.hospital_id) AS total_lab_tests,

    (SELECT COUNT(*)
     FROM Pharmacy p
     WHERE p.hospital_id = h.hospital_id) AS total_pharmacy_transactions

FROM Hospitals h
ORDER BY
    total_appointments
    + total_admissions
    + total_lab_tests
    + total_pharmacy_transactions DESC;

-- 2. Which departments experience the highest appointment and admission workload?
SELECT
    d.department_id,
    d.department_name,

    COUNT(DISTINCT a.appointment_id) AS total_appointments,
    COUNT(DISTINCT ad.admission_id) AS total_admissions,

    COUNT(DISTINCT a.appointment_id)
    + COUNT(DISTINCT ad.admission_id) AS total_workload

FROM Departments d

LEFT JOIN Doctors doc
    ON d.department_id = doc.department_id

LEFT JOIN Appointments a
    ON doc.doctor_id = a.doctor_id

LEFT JOIN Admissions ad
    ON d.department_id = ad.department_id

GROUP BY
    d.department_id,
    d.department_name

ORDER BY total_workload DESC;

-- 3. How is doctor workload distributed based on available appointment or treatment data?
SELECT
    doc.doctor_id,
    doc.first_name,
    doc.last_name,
    doc.specialization,
    COUNT(a.appointment_id) AS total_appointments
FROM Doctors doc
LEFT JOIN Appointments a
    ON doc.doctor_id = a.doctor_id
GROUP BY
    doc.doctor_id
ORDER BY total_appointments DESC;

-- 4. Which patients have the highest healthcare service activity?
SELECT
    p.patient_id,
    p.first_name,
    p.last_name,

    COUNT(DISTINCT a.appointment_id) AS total_appointments,
    COUNT(DISTINCT ad.admission_id) AS total_admissions,

    COUNT(DISTINCT a.appointment_id)
    + COUNT(DISTINCT ad.admission_id) AS total_service_activity

FROM Patients p

LEFT JOIN Appointments a
    ON p.patient_id = a.patient_id

LEFT JOIN Admissions ad
    ON p.patient_id = ad.patient_id

GROUP BY
    p.patient_id

ORDER BY total_service_activity DESC;

-- 5. Which hospitals and departments record the highest admissions?
SELECT
	h.hospital_id,
	h.hospital_name,
    d.department_id,
    d.department_name,
    
    COUNT(a.admission_id) AS total_admission
    
FROM Hospitals h
    
LEFT JOIN Departments d
    ON h.hospital_id = d.hospital_id
    
LEFT JOIN Admissions a
	ON h.hospital_id = a.hospital_id
    
GROUP BY 
	h.hospital_id,
    d.department_id
    
ORDER BY total_admission DESC;

-- 6. What are the patterns in admission type and admission status?
SELECT
    admission_type,
    admission_status,
    COUNT(admission_id) AS total_admissions
FROM Admissions
GROUP BY admission_type, admission_status
ORDER BY total_admissions DESC;

-- 7. What is the average patient length of stay where admission and discharge dates are available?
SELECT
    h.hospital_id,
    h.hospital_name,
    ROUND(AVG(DATEDIFF(a.discharge_date, a.admission_date)), 2) AS average_length_of_stay_days
FROM Hospitals h
JOIN Admissions a
    ON h.hospital_id = a.hospital_id
WHERE a.admission_date IS NOT NULL
  AND a.discharge_date IS NOT NULL
  AND a.discharge_date >= a.admission_date
GROUP BY h.hospital_id, h.hospital_name
ORDER BY average_length_of_stay_days DESC;

-- 8. How are rooms distributed by type and status?
SELECT
	room_type,
    room_status,
    COUNT(*) AS no_of_rooms
FROM Rooms
GROUP BY 
	room_type,
    room_status
ORDER BY no_of_rooms DESC;

-- 9. Which treatments have the highest activity and cost?
SELECT
    treatment_name,
    COUNT(treatment_id) AS total_treatments,
    SUM(treatment_cost) AS total_cost,
    ROUND(AVG(treatment_cost), 2) AS average_cost
FROM Treatments
GROUP BY treatment_name
ORDER BY total_treatments DESC, total_cost DESC;

-- 10. Which laboratory tests or services have the highest volume and cost?
SELECT
    test_name,
    COUNT(lab_test_id) AS total_tests,
    SUM(test_cost) AS total_cost,
    ROUND(AVG(test_cost), 2) AS average_cost
FROM Laboratory
GROUP BY test_name
ORDER BY total_tests DESC, total_cost DESC;

-- 11. Which medicines have the highest pharmacy activity and revenue?
SELECT
    m.medicine_id,
    m.medicine_name,
    COUNT(p.pharmacy_sale_id) AS total_pharmacy_transactions,
    SUM(p.quantity) AS total_quantity,
    SUM(p.quantity * m.unit_price) AS total_revenue
FROM Medicines m
LEFT JOIN Pharmacy p
    ON m.medicine_id = p.medicine_id
GROUP BY
    m.medicine_id,
    m.medicine_name
ORDER BY total_quantity DESC, total_revenue DESC;

-- 12. What is the total billed revenue generated by the hospital?
SELECT
    COUNT(bill_id) AS total_bills,
    SUM(total_amount) AS total_billed_revenue,
    ROUND(AVG(total_amount), 2) AS average_bill_amount
FROM Billing;

-- 13. Which charges contribute most to the total billing amount?
SELECT
    ROUND(SUM(CAST(room_charges AS DECIMAL(10,2))), 2) AS total_room_charges,
    ROUND(SUM(CAST(doctor_charges AS DECIMAL(10,2))), 2) AS total_doctor_charges,
    ROUND(SUM(CAST(medicine_charges AS DECIMAL(10,2))), 2) AS total_medicine_charges,
    ROUND(SUM(CAST(lab_charges AS DECIMAL(10,2))), 2) AS total_lab_charges,
    ROUND(SUM(CAST(other_charges AS DECIMAL(10,2))), 2) AS total_other_charges
FROM Billing;

-- 14. How much revenue has actually been collected through payments?
 SELECT
    ROUND(SUM(CAST(payment_amount AS DECIMAL(10,2))), 2) AS total_collected_amount
FROM Payments
WHERE payment_status = 'Success';

-- 15. Which patients have the largest gaps between billing and payments?
SELECT
    b.patient_id,
    SUM(b.total_amount) AS total_billed,
    SUM(CAST(p.payment_amount AS DECIMAL(10,2))) AS total_paid,
    ROUND(
        SUM(b.total_amount) -
        SUM(CAST(p.payment_amount AS DECIMAL(10,2))),
        2
    ) AS payment_gap
FROM Billing b
JOIN Payments p
    ON b.bill_id = p.bill_id
WHERE p.payment_condition IN ('Fully Paid', 'Partially Paid', 'Overpaid')
GROUP BY b.patient_id
ORDER BY payment_gap DESC;  

-- 16. How do payment methods and payment statuses affect revenue collection?
SELECT
    payment_mode,
    payment_status,
    COUNT(payment_id) AS total_payments,
    ROUND(SUM(CAST(payment_amount AS DECIMAL(10,2))), 2) AS total_amount
FROM Payments
GROUP BY payment_mode, payment_status
ORDER BY total_amount DESC;